export const CHI_CHI_URL = "http://46.225.160.243";
export const DASHBOARD_REDIRECT_TO_LOGIN = "../index.html";
export const HOME_TAB_STORAGE_KEY = "yiding_dashboard_active_tab_v2";
export const ROLE_OWNER = "owner";
export const SCHEDULE_STORAGE_KEY = "yiding_schedule_module_v3";

export const DASHBOARD_TEXT = Object.freeze({
  "zh-Hant": {
    detailEyebrow: "LIVE PANEL",
    chatEyebrow: "MID PANEL",
    help: "說明",
    logout: "退出登录",
    roleAdmin: "最高權限帳號",
    roleViewer: "一般帳號",
    roleOwner: "Owner / Chi Chi 主人",
    readOnly: "唯讀",
    editable: "可編輯",
    allDepartments: "全部部門",
    selectedDepartments: "指定部門",
    menuEmployees: "員工",
    menuSchedule: "班表",
    menuAttendance: "出勤",
    menuInfo: "弈鼎資料",
    menuAccounts: "管理帳號",
    menuChiChi: "Chi Chi",
    employeesTitle: "員工總覽",
    employeesHintAdmin: "完整 Airtable 匯入資料會從舊員工模組同步顯示，這裡先做總覽與捷徑。",
    employeesHintViewer: "此帳號只會看到被授權的部門與員工。",
    employeesDepartment: "部門",
    employeesEmpty: "這個權限範圍目前沒有可顯示的員工。",
    employeesStatActive: "在職員工",
    employeesStatRetired: "離職人員",
    employeesStatDepartments: "可見部門",
    employeesStatSelected: "當前部門",
    employeesOpen: "打開完整員工模組",
    scheduleTitle: "班表總覽",
    scheduleHintAdmin: "完整排班邏輯仍維持舊模組，這裡只做摘要與入口。",
    scheduleHintViewer: "此帳號依權限查看排班，不可跨權限編輯。",
    scheduleMonth: "月份",
    scheduleEmpty: "目前沒有可顯示的班表資料。",
    scheduleRows: "可見列數",
    scheduleAssignments: "已排班格",
    scheduleVisibleDepartments: "可見部門",
    scheduleOpen: "打開完整班表模組",
    attendanceTitle: "出勤區",
    attendanceBody: "保留給之後接打卡、異常與考勤摘要。",
    infoTitle: "弈鼎資料",
    infoBody: "保留給公告、SOP 與內部知識入口。",
    accountsTitle: "帳號管理",
    accountsHint: "YiDing Admin 可以建立、編輯帳號與權限。新增後立刻可登入。",
    accountsAdd: "新增帳號",
    accountsHide: "收起表單",
    accountEdit: "編輯帳號",
    accountSave: "儲存變更",
    accountCreate: "建立帳號",
    accountCancel: "取消",
    accountUsername: "帳號",
    accountPassword: "密碼",
    accountWelcome: "歡迎登入",
    accountPhone: "綁定手機",
    accountEmployeesPermission: "員工模組權限",
    accountSchedulePermission: "班表模組權限",
    accountDepartments: "授權部門",
    accountSuccess: "帳號已建立，現在可以直接登入。",
    accountUpdateSuccess: "帳號已更新。",
    accountDuplicate: "此帳號已存在，請換一個名稱。",
    accountMissing: "必填欄位尚未填完。",
    accountCurrent: "目前登入中",
    accountNoDepartments: "請至少選一個部門，或改回全部部門。",
    accountViewer: "一般帳號",
    accountModuleView: "只看",
    accountModuleEdit: "可編輯",
    currentBinding: "目前綁定",
    phoneEmpty: "尚未綁手機",
    chiChiTitle: "Chi Chi 中控",
    chiChiBadge: "External",
    chiChiPrimary: "Chi Chi 對話入口",
    chiChiBody: "Production 目前只能安全地從這裡打開外部 Chi Chi 視窗；要直接嵌入本站還需要 HTTPS 或反向代理。",
    chiChiOwner: "YiDing Admin 會被視為 owner 身分。",
    chiChiOpen: "在新分頁打開 Chi Chi",
    chiChiWarning: "目前 Chi Chi VPS 只有 HTTP，瀏覽器會阻擋從 HTTPS 首頁直接內嵌。",
    openModule: "打開完整模組",
    permissionScope: "權限範圍",
    permissionAccess: "操作權限",
    permissionDepartments: "部門授權",
    summaryViewer: "只可瀏覽",
    summaryEditor: "可編輯",
    summaryAll: "全部部門",
    summarySelected: "指定部門",
    noDepartmentPermission: "尚未授權任何部門"
  },
  vi: {
    detailEyebrow: "LIVE PANEL",
    chatEyebrow: "MID PANEL",
    help: "Huong dan",
    logout: "Dang xuat",
    roleAdmin: "Tai khoan admin",
    roleViewer: "Tai khoan thuong",
    roleOwner: "Owner / chu Chi Chi",
    readOnly: "Chi xem",
    editable: "Chinh sua",
    allDepartments: "Tat ca bo phan",
    selectedDepartments: "Bo phan chi dinh",
    menuEmployees: "Nhan vien",
    menuSchedule: "Ca lam",
    menuAttendance: "Cham cong",
    menuInfo: "Thong tin YiDing",
    menuAccounts: "Quan ly tai khoan",
    menuChiChi: "Chi Chi",
    employeesTitle: "Tong quan nhan vien",
    employeesHintAdmin: "Du lieu nhan vien day du van nam o module cu; khu nay chi hien tong quan va loi tat.",
    employeesHintViewer: "Tai khoan nay chi thay cac bo phan va nhan vien duoc cap quyen.",
    employeesDepartment: "Bo phan",
    employeesEmpty: "Khong co nhan vien nao trong pham vi quyen hien tai.",
    employeesStatActive: "Nhan vien dang lam",
    employeesStatRetired: "Nhan vien da nghi",
    employeesStatDepartments: "Bo phan co the xem",
    employeesStatSelected: "Bo phan dang chon",
    employeesOpen: "Mo module nhan vien day du",
    scheduleTitle: "Tong quan ca lam",
    scheduleHintAdmin: "Logic xep ca day du van o module cu; khu nay chi hien tom tat va loi vao.",
    scheduleHintViewer: "Tai khoan nay chi xem lich theo quyen, khong duoc sua ngoai pham vi quyen.",
    scheduleMonth: "Thang",
    scheduleEmpty: "Hien tai khong co du lieu ca lam de hien thi.",
    scheduleRows: "So dong co the xem",
    scheduleAssignments: "O da xep ca",
    scheduleVisibleDepartments: "Bo phan co the xem",
    scheduleOpen: "Mo module ca lam day du",
    attendanceTitle: "Khu cham cong",
    attendanceBody: "De danh cho phan ket noi cham cong, bat thuong va tong hop sau nay.",
    infoTitle: "Thong tin YiDing",
    infoBody: "De danh cho thong bao, SOP va cong vao tri thuc noi bo.",
    accountsTitle: "Quan ly tai khoan",
    accountsHint: "YiDing Admin co the tao, sua tai khoan va quyen truy cap. Tao xong dang nhap duoc ngay.",
    accountsAdd: "Them tai khoan",
    accountsHide: "An form",
    accountEdit: "Sua tai khoan",
    accountSave: "Luu thay doi",
    accountCreate: "Tao tai khoan",
    accountCancel: "Huy",
    accountUsername: "Tai khoan",
    accountPassword: "Mat khau",
    accountWelcome: "Loi chao dang nhap",
    accountPhone: "So dien thoai lien ket",
    accountEmployeesPermission: "Quyen module nhan vien",
    accountSchedulePermission: "Quyen module ca lam",
    accountDepartments: "Bo phan duoc cap quyen",
    accountSuccess: "Da tao tai khoan, hien co the dang nhap ngay.",
    accountUpdateSuccess: "Da cap nhat tai khoan.",
    accountDuplicate: "Tai khoan nay da ton tai, hay doi ten khac.",
    accountMissing: "Van con truong bat buoc chua dien.",
    accountCurrent: "Tai khoan dang dang nhap",
    accountNoDepartments: "Hay chon it nhat 1 bo phan, hoac doi ve tat ca bo phan.",
    accountViewer: "Tai khoan thuong",
    accountModuleView: "Chi xem",
    accountModuleEdit: "Duoc sua",
    currentBinding: "Dang lien ket",
    phoneEmpty: "Chua lien ket so dien thoai",
    chiChiTitle: "Trung tam Chi Chi",
    chiChiBadge: "External",
    chiChiPrimary: "Loi vao doi thoai Chi Chi",
    chiChiBody: "Ban production hien chi mo an toan cua so Chi Chi ben ngoai tu day; muon nhung truc tiep vao trang nay thi van can HTTPS hoac reverse proxy.",
    chiChiOwner: "YiDing Admin se duoc xem nhu owner.",
    chiChiOpen: "Mo Chi Chi trong tab moi",
    chiChiWarning: "VPS Chi Chi hien chi co HTTP, trinh duyet se chan viec nhung truc tiep tu trang HTTPS.",
    openModule: "Mo module day du",
    permissionScope: "Pham vi quyen",
    permissionAccess: "Muc thao tac",
    permissionDepartments: "Bo phan duoc cap quyen",
    summaryViewer: "Chi xem",
    summaryEditor: "Duoc sua",
    summaryAll: "Tat ca bo phan",
    summarySelected: "Bo phan chi dinh",
    noDepartmentPermission: "Chua duoc cap quyen bo phan nao"
  },
  en: {
    detailEyebrow: "LIVE PANEL",
    chatEyebrow: "MID PANEL",
    help: "Help",
    logout: "Log out",
    roleAdmin: "Admin account",
    roleViewer: "Standard account",
    roleOwner: "Owner / Chi Chi owner",
    readOnly: "Read only",
    editable: "Editable",
    allDepartments: "All departments",
    selectedDepartments: "Selected departments",
    menuEmployees: "Employees",
    menuSchedule: "Schedule",
    menuAttendance: "Attendance",
    menuInfo: "YiDing Info",
    menuAccounts: "Accounts",
    menuChiChi: "Chi Chi",
    employeesTitle: "Employee Overview",
    employeesHintAdmin: "The full Airtable-import employee data still lives in the legacy module; this area is currently a summary and shortcut layer.",
    employeesHintViewer: "This account only sees the departments and employees it is authorized to access.",
    employeesDepartment: "Department",
    employeesEmpty: "There are no employees available in the current permission scope.",
    employeesStatActive: "Active Employees",
    employeesStatRetired: "Retired Employees",
    employeesStatDepartments: "Visible Departments",
    employeesStatSelected: "Selected Department",
    employeesOpen: "Open Full Employee Module",
    scheduleTitle: "Schedule Overview",
    scheduleHintAdmin: "The full scheduling workflow still lives in the legacy module; this area currently provides a summary and shortcut.",
    scheduleHintViewer: "This account can only view schedules within its permission scope and cannot edit outside it.",
    scheduleMonth: "Month",
    scheduleEmpty: "There is no schedule data available to display right now.",
    scheduleRows: "Visible Rows",
    scheduleAssignments: "Assigned Cells",
    scheduleVisibleDepartments: "Visible Departments",
    scheduleOpen: "Open Full Schedule Module",
    attendanceTitle: "Attendance Zone",
    attendanceBody: "Reserved for future clock-in, exception, and attendance summary integration.",
    infoTitle: "YiDing Info",
    infoBody: "Reserved for announcements, SOPs, and internal knowledge entry points.",
    accountsTitle: "Account Management",
    accountsHint: "YiDing Admin can create and edit accounts and permissions here. New accounts can log in immediately.",
    accountsAdd: "Add Account",
    accountsHide: "Hide Form",
    accountEdit: "Edit Account",
    accountSave: "Save Changes",
    accountCreate: "Create Account",
    accountCancel: "Cancel",
    accountUsername: "Account",
    accountPassword: "Password",
    accountWelcome: "Welcome Message",
    accountPhone: "Bound Phone",
    accountEmployeesPermission: "Employee Module Permission",
    accountSchedulePermission: "Schedule Module Permission",
    accountDepartments: "Authorized Departments",
    accountSuccess: "The account has been created and can log in immediately.",
    accountUpdateSuccess: "The account has been updated.",
    accountDuplicate: "That account already exists. Please choose another name.",
    accountMissing: "Some required fields are still empty.",
    accountCurrent: "Currently signed in",
    accountNoDepartments: "Select at least one department, or switch back to all departments.",
    accountViewer: "Standard account",
    accountModuleView: "View only",
    accountModuleEdit: "Can edit",
    currentBinding: "Current binding",
    phoneEmpty: "No phone linked yet",
    chiChiTitle: "Chi Chi Control",
    chiChiBadge: "External",
    chiChiPrimary: "Chi Chi conversation entry",
    chiChiBody: "Production can currently open the external Chi Chi window safely from here; embedding it directly still needs HTTPS or a reverse proxy.",
    chiChiOwner: "YiDing Admin is treated as the owner role.",
    chiChiOpen: "Open Chi Chi in a new tab",
    chiChiWarning: "The Chi Chi VPS currently only serves HTTP, so browsers block direct embedding from an HTTPS homepage.",
    openModule: "Open Full Module",
    permissionScope: "Permission Scope",
    permissionAccess: "Access Level",
    permissionDepartments: "Authorized Departments",
    summaryViewer: "View only",
    summaryEditor: "Can edit",
    summaryAll: "All departments",
    summarySelected: "Selected departments",
    noDepartmentPermission: "No departments have been authorized yet"
  }
});

export function resolveDashboardText(i18n, key) {
  const locale = i18n.getLocale();
  const bucket = DASHBOARD_TEXT[locale] || DASHBOARD_TEXT["zh-Hant"];
  return bucket[key] || DASHBOARD_TEXT["zh-Hant"][key] || key;
}
